apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-{{ .Values.common.name }}-0
  namespace: {{ .Values.common.namespace }}
  labels:
    app: {{ .Values.statefulset.app }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeName: {{ .Values.common.name }}-pv-0
