apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.common.name }}-service
  namespace: {{ .Values.common.namespace }}

spec:
  selector:
    app: {{ .Values.statefulset.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
