version: "3.8"

services:
  kibana:
    image: kibana:8.17.6
    volumes:
      - ./data/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://host.docker.internal:9200
